/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GestionProfesor;

import DAO.DAOProfesor;
import DAO.DAOProfesorImp;
import Entidad.Profesor;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sistemas10
 */
public class Profesor_Frame extends javax.swing.JFrame {
    DefaultTableModel modelo;
    List<Profesor> listaProfes;
    //SINGLETON
    static private Profesor_Frame instancia = null;    
    static public Profesor_Frame Instanciar(){
        if(instancia == null )
            instancia = new Profesor_Frame();
        System.out.println("ya tenemos esa instancia loco, safa no ma");
        return instancia;
    }
    //****//
    
    /**
     * Creates new form Profesor_Frame
     */
    public Profesor_Frame(){
        initComponents();
        actualizarTabla();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grdProfesores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCurso1 = new javax.swing.JTextField();
        txtCurso2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnOrdenXcod = new javax.swing.JButton();
        btnOrdenXedad = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grdProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Edad", "Telefono", "Correo", "Cod Curso 1", "Cod Curso 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grdProfesores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdProfesoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdProfesores);
        if (grdProfesores.getColumnModel().getColumnCount() > 0) {
            grdProfesores.getColumnModel().getColumn(0).setMaxWidth(20);
            grdProfesores.getColumnModel().getColumn(2).setMaxWidth(50);
            grdProfesores.getColumnModel().getColumn(3).setMaxWidth(100);
            grdProfesores.getColumnModel().getColumn(5).setMaxWidth(70);
            grdProfesores.getColumnModel().getColumn(6).setMaxWidth(70);
        }

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE DOCENTES");

        jButton1.setText("Actualizar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCodigo.setEnabled(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Telefono");

        jLabel6.setText("Correo:");

        jLabel7.setText("Curso 01:");

        jLabel8.setText("Curso 02:");

        jButton2.setText("Eliminar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        btnOrdenXcod.setText("Ordernar Por Codigo");
        btnOrdenXcod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrdenXcodMouseClicked(evt);
            }
        });

        btnOrdenXedad.setText("Ordenar por Edad");
        btnOrdenXedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrdenXedadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtCurso2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar)
                            .addComponent(jButton2)
                            .addComponent(btnOrdenXcod)
                            .addComponent(btnOrdenXedad)
                            .addComponent(jButton5))
                        .addGap(1, 1, 1)))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 494, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnOrdenXcod))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnOrdenXedad))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCurso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:    
        //Object[] fila = {6, "RAAAAA", 24, 123123, "asdasd", 1, 2};
        //modelo.addRow(fila);
        actualizarTabla();
    }//GEN-LAST:event_jButton1MouseClicked

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void grdProfesoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdProfesoresMouseClicked
        // TODO add your handling code here:
        int fila = this.grdProfesores.getSelectedRow();
        String[] registro = new String[grdProfesores.getColumnCount()];
        for(int i = 0; i<grdProfesores.getColumnCount(); i++){
            registro[i] = String.valueOf(this.grdProfesores.getValueAt(fila, i));
        }
        txtCodigo.setText(registro[0]);
        txtNombre.setText(registro[1]);
        txtEdad.setText(registro[2]);
        txtTelefono.setText(registro[3]);
        txtCorreo.setText(registro[4]);
        txtCurso1.setText(registro[5]);
        txtCurso2.setText(registro[6]);
        //String graeack = String.valueOf(this.grdProfesores.getValueAt(fila, 1));
        //txtNombre.setText(graeack);
    }//GEN-LAST:event_grdProfesoresMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        if(txtCodigo.getText() == "" || txtCodigo.getText() == null)return;
        
        Profesor registro = new Profesor();
        registro.setCodigo_profesor(Integer.parseInt(txtCodigo.getText()));
        registro.setNombre_profesor(txtNombre.getText());
        registro.setEdad(Integer.parseInt(txtEdad.getText()));
        registro.setTelefono(Integer.parseInt(txtTelefono.getText()));
        registro.setCorreo(txtCorreo.getText());
        registro.setCurso_01(Integer.parseInt(txtCurso1.getText()));
        registro.setCurso_02(Integer.parseInt(txtCurso2.getText()));
        try{
            DAOProfesor dao = new DAOProfesorImp();
            dao.Modificar(registro);
        }catch (Exception e){
            
        }
        
        actualizarTabla();
    }//GEN-LAST:event_btnModificarMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Profesor registro = new Profesor();
        registro.setCodigo_profesor(Integer.parseInt(txtCodigo.getText()));
        
        try{
            DAOProfesor dao = new DAOProfesorImp();
            dao.Eliminar(registro);
            System.out.println("GRAEACK");
        }catch (Exception e){
            
        }
        
        actualizarTabla();
    }//GEN-LAST:event_jButton2MouseClicked

    private void btnOrdenXedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenXedadMouseClicked
        limpiarTabla(grdProfesores);
        Profesor aea = new Profesor();
        for (;;) {
            char flag = 0;
            for (int i = 0; i < listaProfes.size() - 1; i++) {
                if (listaProfes.get(i).getEdad() > listaProfes.get(i + 1).getEdad()) {
                    aea = listaProfes.get(i);
                    listaProfes.set(i, listaProfes.get(i + 1));
                    listaProfes.set(i + 1, aea);
                    flag = 1;
                }
            }
            if (flag == 0) {
                break;
            }
        }
        listar(listaProfes);
    }//GEN-LAST:event_btnOrdenXedadMouseClicked

    private void btnOrdenXcodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenXcodMouseClicked
        limpiarTabla(grdProfesores);
        Profesor aea = new Profesor();
        for (;;) {
            char flag = 0;
            for (int i = 0; i < listaProfes.size() - 1; i++) {
                if (listaProfes.get(i).getCodigo_profesor() > listaProfes.get(i + 1).getCodigo_profesor()) {
                    aea = listaProfes.get(i);
                    listaProfes.set(i, listaProfes.get(i + 1));
                    listaProfes.set(i + 1, aea);
                    flag = 1;
                }
            }
            if (flag == 0) {
                break;
            }
        }
        listar(listaProfes);
    }//GEN-LAST:event_btnOrdenXcodMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profesor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profesor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profesor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profesor_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profesor_Frame().setVisible(true);
            }
        });
    }
    
    protected void actualizarTabla(){
        limpiarTabla(grdProfesores);
        DAOProfesor dao = new DAOProfesorImp();
        
        
        try{
            listaProfes = (dao.listar());
            listar(listaProfes);
            /**/
            
            /*modelo = (DefaultTableModel) grdProfesores.getModel();
            Object[] fila = new Object[modelo.getColumnCount()];
            for(int i = 0; i < listaProfes.size(); i++){
                fila[0] = listaProfes.get(i).getCodigo_profesor();
                fila[1] = listaProfes.get(i).getNombre_profesor();
                fila[2] = listaProfes.get(i).getEdad();
                fila[3] = listaProfes.get(i).getTelefono();
                fila[4] = listaProfes.get(i).getCorreo();
                fila[5] = listaProfes.get(i).getCurso_01();
                fila[6] = listaProfes.get(i).getCurso_02();
                modelo.addRow(fila);
            }*/
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    
    
    public void limpiarTabla(JTable tabla){
        try {
            DefaultTableModel modelo=(DefaultTableModel) tabla.getModel();
            int filas=tabla.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }
    
    
    
    private void listar(List<Profesor> registros){
        modelo = (DefaultTableModel) grdProfesores.getModel();
            Object[] fila = new Object[modelo.getColumnCount()];
            for(int i = 0; i < registros.size(); i++){
                fila[0] = registros.get(i).getCodigo_profesor();
                fila[1] = registros.get(i).getNombre_profesor();
                fila[2] = registros.get(i).getEdad();
                fila[3] = registros.get(i).getTelefono();
                fila[4] = registros.get(i).getCorreo();
                fila[5] = registros.get(i).getCurso_01();
                fila[6] = registros.get(i).getCurso_02();
                modelo.addRow(fila);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnOrdenXcod;
    private javax.swing.JButton btnOrdenXedad;
    private javax.swing.JTable grdProfesores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtCurso1;
    private javax.swing.JTextField txtCurso2;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
